version: '2'
services:  
   mysql:
       image: mysql:5.7
       restart: always
       ports:
          - "3301:3306"
       volumes: 
          - ./mysql/data:/var/lib/mysql
          - ./mysql/conf:/etc/mysql/conf.d
       environment:
          - "MYSQL_ROOT_PASSWORD=zfb19930302"
          - "MYSQL_DATABASE=blog"
          - "MYSQL_USER=admin"
          - "MYSQL_PASSWORD=zfb19930423"
   php-fpm:  
       build: ./php
       restart: always
       volumes: 
          - ./new-admin:/var/www/html
          #- ./php/etc:/usr/local/etc
          #- ./php/log:/etc/var/log/php
       expose: 
          - "9000"
       stdin_open: true
       tty: true
       depends_on: 
          - mysql
          - elasticsearch
   nginx: 
       image: nginx
       restart: always
       ports: 
          - "83:80"
       volumes: 
          - ./new-admin/:/var/www/html
          - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
          - ./nginx/nginx.conf/:/etc/nginx/nginx.conf
          - ./nginx/error.log:/var/www/error.log
          - ./nginx/access.log:/var/www/access.log
       depends_on: 
          - php-fpm
   redis: 
       image: redis
       restart: always
       ports: 
          - "6379:6379"
   elasticsearch: 
      image: elasticsearch:7.10.1
      ports: 
          - "9200:9200"
          - "9300:9300"
      environment:
          - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
          - cluster.name=tommy-es
          - bootstrap.memory_lock=true
          - discovery.type=single-node
      volumes:
          - ./es-data:/usr/share/elasticsearch/data